Electronic_Store/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Electronic_Store.Models;
using System.Data.Entity;

namespace Electronic_Store.Areas.Admin.Controllers
{

    public class CategoryController : Controller
    {
        electronic_storeEntities db = new electronic_storeEntities();
        // GET: Admin/Category
        public ActionResult Index()
        {
            ViewBag.categorys = db.categories.ToList();
            return View();
        }

        [HttpGet]
        public ActionResult Add_Category()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add_Category(category category)
        {
            if(ModelState.IsValid)
            {
                db.categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View("Add_Category");
            }
        }

        [HttpGet]
        public ActionResult Update_Category(int id)
        {
            var category = db.categories.Find(id);
            return View("Update_Category",category);
        }
        [HttpPost]
        public ActionResult Update_Category(category category)
        {
            if(ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View("Update_Category");
            }
        }
        public ActionResult Delete_Category(int id)
        {
            var category = db.categories.Find(id);
            db.categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Electronic_Store/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Electronic_Store.Models;
using System.Data.Entity;
using System.Security.Cryptography;
using System.Text;

namespace Electronic_Store.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        electronic_storeEntities db = new electronic_storeEntities();
        // GET: Admin/User
        public ActionResult Users()
        {
            ViewBag.user = db.users.ToList();
            return View();
        }

        public static string HashSHA1Decryption(string value)
        {
            var shaSHA1 = System.Security.Cryptography.SHA1.Create();
            var inputEncodingBytes = Encoding.ASCII.GetBytes(value);
            var hashString = shaSHA1.ComputeHash(inputEncodingBytes);

            var stringBuilder = new StringBuilder();
            for (var x = 0; x < hashString.Length; x++)
            {
                stringBuilder.Append(hashString[x].ToString("X2"));
            }
            return stringBuilder.ToString();
        }

        public ActionResult Delete_User(int id)
        {
            var user = db.users.Find(id);
            db.users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Users");
        }

        [HttpGet]
        public ActionResult Add_User()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add_User(user user, HttpPostedFileBase photo)
        {
            if(ModelState.IsValid)
            {
                if (photo != null)
                {
                    photo.SaveAs(Server.MapPath("/Areas/Admin/Assets/images/" + photo.FileName));
                    user.images = photo.FileName;
                }
                else
                {
                    string picture = "no-image.jpg";
                    user.images = picture;
                }
                var encrypt = HashSHA1Decryption(user.password);
                var encrypts = HashSHA1Decryption(user.confirmpassword);
                user.password = encrypt;
                user.confirmpassword = encrypts;
                user.status = true;
                db.users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Users");
            }
            else
            {
                return View("Add_User");
            }
        }
    }
}

Electronic_Store/Areas/Admin/Views/Shared/Header.cshtml
<div class="sticky-header header-section ">
    <div class="header-left">
        <!--toggle button start-->
        <button id="showLeftPush"><i class="fa fa-bars"></i></button>
        <!--toggle button end-->
        <div class="profile_details_left">
            <!--notifications of menu start -->
            <ul class="nofitications-dropdown">
                <li class="dropdown head-dpdn">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">4</span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="notification_header">
                                <h3>You have 3 new messages</h3>
                            </div>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="/Areas/Admin/Assets/images/1.jpg" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor amet</p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li class="odd">
                            <a href="#">
                                <div class="user_img"><img src="/Areas/Admin/Assets/images/4.jpg" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="/Areas/Admin/Assets/images/3.jpg" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="/Areas/Admin/Assets/images/2.jpg" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <div class="notification_bottom">
                                <a href="#">See all messages</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown head-dpdn">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell"></i><span class="badge blue">4</span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="notification_header">
                                <h3>You have 3 new notification</h3>
                            </div>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="/Areas/Admin/Assets/images/4.jpg" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor amet</p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li class="odd">
                            <a href="#">
                                <div class="user_img"><img src="/Areas/Admin/Assets/images/1.jpg" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="/Areas/Admin/Assets/images/3.jpg" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="user_img"><img src="/Areas/Admin/Assets/images/2.jpg" alt=""></div>
                                <div class="notification_desc">
                                    <p>Lorem ipsum dolor amet </p>
                                    <p><span>1 hour ago</span></p>
                                </div>
                                <div class="clearfix"></div>
                            </a>
                        </li>
                        <li>
                            <div class="notification_bottom">
                                <a href="#">See all notifications</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown head-dpdn">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-tasks"></i><span class="badge blue1">8</span></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="notification_header">
                                <h3>You have 8 pending task</h3>
                            </div>
                        </li>
                        <li>
                            <a href="#">
                                <div class="task-info">
                                    <span class="task-desc">Database update</span><span class="percentage">40%</span>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="progress progress-striped active">
                                    <div class="bar yellow" style="width:40%;"></div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="task-info">
                                    <span class="task-desc">Dashboard done</span><span class="percentage">90%</span>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="progress progress-striped active">
                                    <div class="bar green" style="width:90%;"></div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="task-info">
                                    <span class="task-desc">Mobile App</span><span class="percentage">33%</span>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="progress progress-striped active">
                                    <div class="bar red" style="width: 33%;"></div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <div class="task-info">
                                    <span class="task-desc">Issues fixed</span><span class="percentage">80%</span>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="progress progress-striped active">
                                    <div class="bar  blue" style="width: 80%;"></div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <div class="notification_bottom">
                                <a href="#">See all pending tasks</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
            <div class="clearfix"> </div>
        </div>
        <!--notification menu end -->
        <div class="clearfix"> </div>
    </div>
    <div class="header-right">


        <!--search-box-->
        <div class="search-box">
            <form class="input">
                <input class="sb-search-input input__field--madoka" placeholder="Search..." type="search" id="input-31" />
                <label class="input__label" for="input-31">
                    <svg class="graphic" width="100%" height="100%" viewBox="0 0 404 77" preserveAspectRatio="none">
                        <path d="m0,0l404,0l0,77l-404,0l0,-77z" />
                    </svg>
                </label>
            </form>
        </div><!--//end-search-box-->

        <div class="profile_details">
            <ul>
                <li class="dropdown profile_details_drop">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <div class="profile_img">
                            <span class="prfil-img"><img src="/Areas/Admin/Assets/images/2.jpg" alt=""> </span>
                            <div class="user-name">
                                <p>Admin Name</p>
                                <span>Administrator</span>
                            </div>
                            <i class="fa fa-angle-down lnr"></i>
                            <i class="fa fa-angle-up lnr"></i>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                    <ul class="dropdown-menu drp-mnu">
                        <li> <a href="#"><i class="fa fa-cog"></i> Settings</a> </li>
                        <li> <a href="#"><i class="fa fa-user"></i> My Account</a> </li>
                        <li> <a href="#"><i class="fa fa-suitcase"></i> Profile</a> </li>
                        <li> <a href="#"><i class="fa fa-sign-out"></i> Logout</a> </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
    <div class="clearfix"> </div>
</div>

Electronic_Store/Areas/Admin/Views/Shared/Left_Menu.cshtml
<div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
    <!--left-fixed -navigation-->
    <aside class="sidebar-left">
        <nav class="navbar navbar-inverse">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1><a class="navbar-brand" href="index.html"><span class="fa fa-area-chart"></span> Glance<span class="dashboard_text">Design dashboard</span></a></h1>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="treeview">
                        <a href="@Url.Action("Index","Home")">
                            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        </a>
                    </li>
                    @*<li class="treeview">
                        <a href="#">
                            <i class="fa fa-laptop"></i>
                            <span>Components</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="grids.html"><i class="fa fa-angle-right"></i> Grids</a></li>
                            <li><a href="media.html"><i class="fa fa-angle-right"></i> Media Css</a></li>
                        </ul>
                    </li>*@
                    <li class="treeview">
                        <a href="@Url.Action("Chart","Home")">
                            <i class="fa fa-pie-chart"></i> <span>Charts</span>
                            <span class="label label-primary pull-right">new</span>
                        </a>
                    </li>
                    <li class="treeview">
                    @*<li class="treeview">
                        <a href="#">
                            <i class="fa fa-laptop"></i>
                            <span>UI Elements</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="general.html"><i class="fa fa-angle-right"></i> General</a></li>
                            <li><a href="icons.html"><i class="fa fa-angle-right"></i> Icons</a></li>
                            <li><a href="buttons.html"><i class="fa fa-angle-right"></i> Buttons</a></li>
                            <li><a href="typography.html"><i class="fa fa-angle-right"></i> Typography</a></li>
                        </ul>
                    </li>*@
                    <li>
                        <a href="@Url.Action("Product","Home")">
                            <i class="fa fa-th"></i> <span>Product</span>
                            @*<small class="label pull-right label-info">08</small>*@
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Category")">
                            <i class="fa fa-table"></i> <span>Category</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Customer","Customer")">
                            <i class="fa fa-user"></i> <span>Customer</span>
                            @*<small class="label pull-right label-info">08</small>*@
                        </a>
                    </li>
                    @*<li class="treeview">
            <a href="#">
                <i class="fa fa-edit"></i> <span>Forms</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="forms.html"><i class="fa fa-angle-right"></i> General Forms</a></li>
                <li><a href="validation.html"><i class="fa fa-angle-right"></i> Form Validations</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-table"></i> <span>Tables</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="tables.html"><i class="fa fa-angle-right"></i> Simple tables</a></li>
            </ul>
        </li>*@
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-envelope"></i> <span>Mailbox </span>
                            <i class="fa fa-angle-left pull-right"></i>@*<small class="label pull-right label-info1">08</small>*@<span class="label label-primary1 pull-right">02</span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Contact","Contact")"><i class="fa fa-angle-right"></i> Mail Inbox </a></li>
                            <li><a href=""><i class="fa fa-angle-right"></i> Compose Mail </a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="@Url.Action("Users","User")">
                            <i class="fa fa-folder"></i> <span>Admin</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Users","User")"><i class="fa fa-angle-right"></i> User Management</a></li>
                            @*<li><a href=""><i class="fa fa-angle-right"></i> Register</a></li>
                            <li><a href=""><i class="fa fa-angle-right"></i> 404 Error</a></li>
                            <li><a href=""><i class="fa fa-angle-right"></i> 500 Error</a></li>
                            <li><a href=""><i class="fa fa-angle-right"></i> Blank Page</a></li>*@
                        </ul>
                    </li>
                    <li class="header">LABELS</li>
                    <li><a href="#"><i class="fa fa-angle-right text-red"></i> <span>Important</span></a></li>
                    <li><a href="#"><i class="fa fa-angle-right text-yellow"></i> <span>Warning</span></a></li>
                    <li><a href="#"><i class="fa fa-angle-right text-aqua"></i> <span>Information</span></a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
    </aside>
</div>

Electronic_Store/Areas/Admin/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

    <!-- Bootstrap Core CSS -->
    <link href="@Url.Content("~/Areas/Admin/Assets/css/bootstrap.css")" rel='stylesheet' type='text/css' />

    <!-- Custom CSS -->
    <link href="@Url.Content("~/Areas/Admin/Assets/css/style.css")" rel='stylesheet' type='text/css' />

    <!-- font-awesome icons CSS -->
    <link href="@Url.Content("~/Areas/Admin/Assets/css/font-awesome.css")" rel="stylesheet">
    <!-- //font-awesome icons CSS-->
    <!-- side nav css file -->
    <link href="@Url.Content("~/Areas/Admin/Assets/css/SidebarNav.min.css")" media='all' rel='stylesheet' type='text/css' />
    <!-- //side nav css file -->
    <!-- js-->
    <script src="@Url.Content("~/Areas/Admin/Assets/js/jquery-1.11.1.min.js")"></script>
    <script src="@Url.Content("~/Areas/Admin/Assets/js/modernizr.custom.js")"></script>
    <!--CKEditor-->
    <script src="@Url.Content("~/Areas/Admin/Assets/ckeditor/ckeditor.js")"></script>
    <!--webfonts-->
    <link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet">
    <!--//webfonts-->
    <!-- chart -->
    <script src="@Url.Content("~/Areas/Admin/Assets/js/Chart.js")"></script>
    <!-- //chart -->
    <!-- Metis Menu -->
    <script src="@Url.Content("~/Areas/Admin/Assets/js/metisMenu.min.js")"></script>
    <script src="@Url.Content("~/Areas/Admin/Assets/js/custom.js")"></script>
    <link href="@Url.Content("~/Areas/Admin/Assets/css/custom.css")" rel="stylesheet">
    <!--//Metis Menu -->
    <style>
        #chartdiv {
            width: 100%;
            height: 295px;
        }
    </style>
    <!--pie-chart --><!-- index page sales reviews visitors pie chart -->
    <script src="@Url.Content("~/Areas/Admin/Assets/js/pie-chart.js")" type="text/javascript"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            $('#demo-pie-1').pieChart({
                barColor: '#2dde98',
                trackColor: '#eee',
                lineCap: 'round',
                lineWidth: 8,
                onStep: function (from, to, percent) {
                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');
                }
            });

            $('#demo-pie-2').pieChart({
                barColor: '#8e43e7',
                trackColor: '#eee',
                lineCap: 'butt',
                lineWidth: 8,
                onStep: function (from, to, percent) {
                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');
                }
            });

            $('#demo-pie-3').pieChart({
                barColor: '#ffc168',
                trackColor: '#eee',
                lineCap: 'square',
                lineWidth: 8,
                onStep: function (from, to, percent) {
                    $(this.element).find('.pie-value').text(Math.round(percent) + '%');
                }
            });


        });

    </script>
    <!-- //pie-chart --><!-- index page sales reviews visitors pie chart -->
    <!-- requried-jsfiles-for owl -->
    <link href="@Url.Content("~/Areas/Admin/Assets/css/owl.carousel.css")" rel="stylesheet">
    <script src="@Url.Content("~/Areas/Admin/Assets/js/owl.carousel.js")"></script>
    <script>
        $(document).ready(function () {
            $("#owl-demo").owlCarousel({
                items: 3,
                lazyLoad: true,
                autoPlay: true,
                pagination: true,
                nav: true,
            });
        });
    </script>
    <!-- //requried-jsfiles-for owl -->
</head>
<body class="cbp-spmenu-push">
    <div class="main-content">
        @Html.Partial("Left_Menu")
        @Html.Partial("Header")
        @RenderBody()
        @Html.Partial("Footer")
    </div>
</body>
</html>